-- SPDX-License-Identifier: AGPL-3.0-or-later

-- Adds each node's own SSH identity - see PLANNING.md's peer-to-peer model
-- transfer decision. ssh_public_key is the node's own client identity,
-- generated locally by `sparky-agent setup` (agent/provision) and reported
-- once the agent connects - the private key never leaves the node, the
-- opposite asymmetry from bearer_token_hash (which the central app
-- generates and hands TO the node). All three columns are nullable: an
-- already-registered node has none of them until its agent reconnects on
-- an upgraded binary and reports them - no backfill is possible for data
-- that has never existed.
--
-- ssh_host_public_key is NOT this node's own identity - it's the node's
-- system sshd host key (/etc/ssh/ssh_host_ed25519_key.pub, OS-managed, not
-- generated by Sparky), reported so a peer pulling FROM this node can pin
-- trust for that one connection instead of blind TOFU.
--
-- default_transfer_interface names one of this node's own
-- node_network_interfaces rows by name, not by FK - see that table's own
-- migration for why. NULL means "Fastest" (auto-pick the highest reported
-- link speed), never a distinct "not configured" state requiring its own
-- sentinel.
ALTER TABLE nodes ADD COLUMN ssh_public_key text;
ALTER TABLE nodes ADD COLUMN ssh_host_public_key text;
ALTER TABLE nodes ADD COLUMN default_transfer_interface text;
