// SPDX-License-Identifier: AGPL-3.0-or-later

// Package provision performs idempotent local OS-level setup for a
// bare-metal sparky-agent install - the serviceloop system account, its
// model storage home directory, and GPU-passthrough group membership. See
// cmd/sparky-agent's `setup` subcommand, the only caller of this package -
// PLANNING.md's 2026-08-07 Decisions Log entry explains why this logic
// lives in the agent binary rather than only in
// scripts/packaging/lib/agent-common.sh (bash), which it replaces: real
// go test coverage, and one implementation instead of duplicating
// useradd/usermod handling across three install methods.
package provision

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// runner is a fakeable seam for shelling out - same pattern as
// agent/telemetry's commandRunner, narrowed to just error (exit status)
// since nothing here needs to parse stdout.
type runner func(ctx context.Context, name string, args ...string) error

func runCommand(ctx context.Context, name string, args ...string) error {
	return exec.CommandContext(ctx, name, args...).Run()
}

// serviceloopHome is serviceloop's home directory - deliberately under
// /opt/sparky rather than the useradd default of /home/serviceloop, since
// the systemd unit's ProtectHome=true makes /home/* inaccessible to the
// running process regardless of whether the directory exists there.
const serviceloopHome = "/opt/sparky/serviceloop"

// DefaultSSHKeyPath is where EnsureSSHKeypair puts this node's own SSH
// client identity, and the default for SPARKY_SSH_KEY_PATH. Under
// serviceloopHome rather than a real /home directory for the same
// ProtectHome=true reason serviceloopHome itself is.
const DefaultSSHKeyPath = serviceloopHome + "/.ssh/id_ed25519"

// DefaultSSHHostKeyPath is the default for SPARKY_SSH_HOST_KEY_PATH - the
// system sshd's own ed25519 host public key (OS-managed, not generated by
// Sparky). Not universal across every distro/hardened image; the env var
// override exists for that reason.
const DefaultSSHHostKeyPath = "/etc/ssh/ssh_host_ed25519_key.pub"

// Provisioner performs the provisioning steps below. Requires root - see
// cmd/sparky-agent's own explicit check before constructing one. Not safe
// for concurrent use (mirrors telemetry.Collector) - not a concern in
// practice, since a `setup` invocation only ever runs these once, in order.
type Provisioner struct {
	run        runner
	sshKeyPath string
}

// New constructs a Provisioner that shells out for real.
func New() *Provisioner {
	return &Provisioner{run: runCommand, sshKeyPath: DefaultSSHKeyPath}
}

// EnsureServiceloopUser creates the serviceloop system account if it
// doesn't already exist - idempotent, safe to call on every install and
// upgrade.
func (p *Provisioner) EnsureServiceloopUser(ctx context.Context) error {
	if err := p.run(ctx, "id", "-u", "serviceloop"); err == nil {
		return nil
	}
	if err := p.run(ctx, "useradd", "--system", "--no-create-home", "--home-dir", serviceloopHome, "--shell", "/usr/sbin/nologin", "serviceloop"); err != nil {
		return fmt.Errorf("useradd serviceloop: %w", err)
	}
	return nil
}

// EnsureModelStorageDir creates serviceloop's home directory - also the
// parent of the bare-metal runtime backend's default
// SPARKY_MODEL_STORAGE_PATH (agent/config's bareMetalDefaultModelStoragePath).
// Must run after EnsureServiceloopUser - resolving the directory's
// ownership needs that account to already exist.
func (p *Provisioner) EnsureModelStorageDir(ctx context.Context) error {
	if err := p.run(ctx, "install", "-d", "-o", "serviceloop", "-g", "serviceloop", "-m", "0750", serviceloopHome); err != nil {
		return fmt.Errorf("create %s: %w", serviceloopHome, err)
	}
	return nil
}

// EnsureGPUGroupMembership joins serviceloop to whichever of video/render
// actually exists on this host - distro/driver-dependent, so both are
// attempted rather than guessed; joining a group that turns out to be
// irrelevant is harmless, but silently skipping the one that does matter
// would leave the agent unable to see any GPU device node at all.
func (p *Provisioner) EnsureGPUGroupMembership(ctx context.Context) error {
	for _, grp := range []string{"video", "render"} {
		if err := p.run(ctx, "getent", "group", grp); err != nil {
			continue
		}
		if err := p.run(ctx, "usermod", "-aG", grp, "serviceloop"); err != nil {
			return fmt.Errorf("join serviceloop to group %s: %w", grp, err)
		}
	}
	return nil
}

// EnsureSSHKeypair generates this node's own SSH client identity - an
// ed25519 keypair with no passphrase, owned by serviceloop, private key
// 0600 - if one doesn't already exist. Idempotent: an existing private key
// is never overwritten, so re-running setup (every package upgrade does)
// never rotates the identity a peer or the central app already knows. The
// private key never leaves the node; only the public half is reported
// (agent/connection's hello). Must run after EnsureServiceloopUser and
// EnsureModelStorageDir. No passphrase because the agent has no human to
// type one - the key's protection is file ownership and mode, same as any
// service account key.
func (p *Provisioner) EnsureSSHKeypair(ctx context.Context) error {
	keyPath := p.sshKeyPath
	sshDir := filepath.Dir(keyPath)
	if err := p.run(ctx, "install", "-d", "-o", "serviceloop", "-g", "serviceloop", "-m", "0700", sshDir); err != nil {
		return fmt.Errorf("create %s: %w", sshDir, err)
	}
	if _, err := os.Stat(keyPath); err == nil {
		return nil
	}
	if err := p.run(ctx, "ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "sparky-agent", "-f", keyPath); err != nil {
		return fmt.Errorf("ssh-keygen %s: %w", keyPath, err)
	}
	for _, f := range []string{keyPath, keyPath + ".pub"} {
		if err := p.run(ctx, "chown", "serviceloop:serviceloop", f); err != nil {
			return fmt.Errorf("chown %s: %w", f, err)
		}
	}
	if err := p.run(ctx, "chmod", "0600", keyPath); err != nil {
		return fmt.Errorf("chmod %s: %w", keyPath, err)
	}
	return nil
}

// ReadSSHPublicKey returns the public key at path (a .pub file) as a
// single normalized "<type> <base64>" line with any comment stripped, or
// "" if the file is missing, unreadable, or empty. Best-effort by design,
// not an error: a node without a keypair (setup not yet re-run since this
// feature shipped) or without sshd (a destination-only node, for host
// keys) still connects and does everything except take part in
// peer-to-peer transfer - see agentproto.Hello.
func ReadSSHPublicKey(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) >= 2 && !strings.HasPrefix(fields[0], "#") {
			return fields[0] + " " + fields[1]
		}
	}
	return ""
}
